function ServicesPreview() {
      const services = [
          {
                icon: "🏢",
                      title: "Business & CAC Services",
                            description:
                                    "CAC registration, post-incorporation services, annual returns, and business documentation.",
                                        },
                                            {
                                                  icon: "🪪",
                                                        title: "Identity Services",
                                                              description:
                                                                      "Support for NIN, BVN, and other identity-related documentation services.",
                                                                          },
                                                                              {
                                                                                    icon: "💻",
                                                                                          title: "Web Development",
                                                                                                description:
                                                                                                        "Modern and responsive websites for individuals, startups, and businesses.",
                                                                                                            },
                                                                                                              ];

                                                                                                                return (
                                                                                                                    <section className="py-5">
                                                                                                                          <div className="container">

                                                                                                                                  <div className="text-center mb-5">
                                                                                                                                            <h2 className="fw-bold">
                                                                                                                                                        Our Services
                                                                                                                                                                  </h2>

                                                                                                                                                                            <p className="text-muted">
                                                                                                                                                                                        Practical solutions designed to help your business operate and
                                                                                                                                                                                                    grow.
                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                              <div className="row g-4">
                                                                                                                                                                                                                                        {services.map((service) => (
                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                  className="col-md-4"
                                                                                                                                                                                                                                                                                key={service.title}
                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                          <div className="card h-100 border-0 shadow-sm p-4">

                                                                                                                                                                                                                                                                                                                          <div className="fs-1 mb-3">
                                                                                                                                                                                                                                                                                                                                            {service.icon}
                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                            <h3 className="h5 fw-bold">
                                                                                                                                                                                                                                                                                                                                                                                              {service.title}
                                                                                                                                                                                                                                                                                                                                                                                                              </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-muted mb-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                {service.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default ServicesPreview;
