function Services() {
      return (
          <section className="container py-5">
                <h2 className="text-center fw-bold mb-5">Our Services</h2>

                      <div className="row g-4">

                              <div className="col-md-4">
                                        <div className="card h-100 shadow-sm">
                                                    <div className="card-body text-center">
                                                                  <h4>CAC Registration</h4>
                                                                                <p>
                                                                                                Business Name, Limited Company,
                                                                                                                NGO registration and post-incorporation services.
                                                                                                                              </p>
                                                                                                                                          </div>
                                                                                                                                                    </div>
                                                                                                                                                            </div>

                                                                                                                                                                    <div className="col-md-4">
                                                                                                                                                                              <div className="card h-100 shadow-sm">
                                                                                                                                                                                          <div className="card-body text-center">
                                                                                                                                                                                                        <h4>Identity Services</h4>
                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                      NIN updates, BVN services,
                                                                                                                                                                                                                                                      Tax Identification Number and documentation.
                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                          <div className="col-md-4">
                                                                                                                                                                                                                                                                                                                    <div className="card h-100 shadow-sm">
                                                                                                                                                                                                                                                                                                                                <div className="card-body text-center">
                                                                                                                                                                                                                                                                                                                                              <h4>Web & AI Solutions</h4>
                                                                                                                                                                                                                                                                                                                                                            <p>
                                                                                                                                                                                                                                                                                                                                                                            Professional websites,
                                                                                                                                                                                                                                                                                                                                                                                            AI automation and custom software development.
                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default Services;
