function About() {
      return (
          <main>
                <section className="container text-center py-5">
                        <h1 className="display-5 fw-bold">
                                  About DeenByte
                                          </h1>

                                                  <p className="lead mt-3">
                                                            DeenByte Technologies provides reliable digital
                                                                      services that help individuals and businesses
                                                                                operate, grow, and succeed.
                                                                                        </p>
                                                                                              </section>

                                                                                                    <section className="container py-4">
                                                                                                            <div className="row g-4">

                                                                                                                      <div className="col-md-6">
                                                                                                                                  <div className="card h-100 shadow-sm">
                                                                                                                                                <div className="card-body">
                                                                                                                                                                <h2 className="h4 fw-bold">
                                                                                                                                                                                  Our Mission
                                                                                                                                                                                                  </h2>

                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                    Our mission is to make digital and business
                                                                                                                                                                                                                                                      services easier, faster, and more accessible
                                                                                                                                                                                                                                                                        to individuals and businesses across Nigeria.
                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                      <div className="col-md-6">
                                                                                                                                                                                                                                                                                                                                                  <div className="card h-100 shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                <div className="card-body">
                                                                                                                                                                                                                                                                                                                                                                                <h2 className="h4 fw-bold">
                                                                                                                                                                                                                                                                                                                                                                                                  Our Vision
                                                                                                                                                                                                                                                                                                                                                                                                                  </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    We aim to become a trusted technology and
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      business services partner for businesses
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        looking to build, automate, and grow.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <section className="container text-center py-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2 className="fw-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  What We Do
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="mt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            We combine business services and technology to
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      provide practical solutions for modern businesses.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="row g-4 mt-3">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="col-md-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="h5 fw-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Business Services
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                CAC registration, post-incorporation services,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              and business documentation.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="col-md-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="h5 fw-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Identity Services
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Identity-related services including NIN,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            BVN, and other documentation support.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="col-md-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="h5 fw-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Technology Solutions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Websites, software solutions, AI automation,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          and digital business tools.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default About;
